name: aqsolpred
channels:
- rdkit
- conda-forge
- defaults
dependencies:
    - libgcc=5.2.0
    - rdkit
    - pip
    - pip:
        - streamlit==1.12.0
        - pandas>=1.3.5
        - numpy==1.20
        - scikit-learn==0.22.2.post1
        - mordred
        - xgboost==1.0.2
        - click==8.0
        - cython
